# Generated by Django 4.2.4 on 2023-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_video_all_topic_video_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="useritem",
            name="imagefile",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
